---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-injector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.25.0

      helm:
        valueFiles:
          - $values/release/values.yaml

    - repoURL: https://github.com/IanHewlett/demo-platform-service-vault-injector.git
      ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
